services:
  - type: web
    name: sick-one-tattoos-consent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GMAIL_APP_PASSWORD
        value: aelczljtawyrobbq
    plan: free
